leftnav:
- identifier: ac53cbde-5f80-dfed-cf91-80c97c88acee
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 34f1a99d-c912-2193-c437-231b1fc08afe
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 1b685882-0e39-dbc6-ba03-dc47858871bd
  name: Instructor Insights
  url: /pages/instructor-insights/
  weight: 30
- identifier: 2d69a0de-0f58-08a2-3880-f4a28f594d72
  name: Course History
  parent: 1b685882-0e39-dbc6-ba03-dc47858871bd
  url: /pages/instructor-insights/course-history
  weight: 40
- identifier: e612a220-f47d-26cb-1df4-1379920545d8
  name: A Unified Curriculum with Bayesian Statistics
  parent: 1b685882-0e39-dbc6-ba03-dc47858871bd
  url: /pages/instructor-insights/a-unified-curriculum-with-bayesian-statistics
  weight: 50
- identifier: c087d0ea-b9b0-a8e6-9867-02428a46325e
  name: Targeted Readings and Online Reading Questions
  parent: 1b685882-0e39-dbc6-ba03-dc47858871bd
  url: /pages/instructor-insights/targeted-readings-and-questions
  weight: 60
- identifier: 47372cd3-e919-0e97-d65a-ddc960247454
  name: Problem Set Checkers
  parent: 1b685882-0e39-dbc6-ba03-dc47858871bd
  url: /pages/instructor-insights/problem-set-checker
  weight: 70
- identifier: a3b80720-d701-2da0-a420-760cbd667430
  name: Clicker Questions
  parent: 1b685882-0e39-dbc6-ba03-dc47858871bd
  url: /pages/instructor-insights/clicker-questions
  weight: 80
- identifier: 3f220109-a2fa-c42b-47f0-b1be29e4f8ab
  name: Trust in an Active Learning Classroom
  parent: 1b685882-0e39-dbc6-ba03-dc47858871bd
  url: /pages/instructor-insights/trust-in-an-active-learning-classroom
  weight: 90
- identifier: bcc7c9ac-7b81-71b2-3cc4-5d69d98f83cd
  name: Co-Teaching
  parent: 1b685882-0e39-dbc6-ba03-dc47858871bd
  url: /pages/instructor-insights/co-teaching
  weight: 100
- identifier: 12233ebe-f550-072f-c1cb-c292891e2f81
  name: Challenges
  parent: 1b685882-0e39-dbc6-ba03-dc47858871bd
  url: /pages/instructor-insights/challenges
  weight: 110
- identifier: 1423305c-9876-32ae-3be2-b0d0096865f3
  name: Readings and Reading Questions
  parent: 1b685882-0e39-dbc6-ba03-dc47858871bd
  url: /pages/instructor-insights/readings-and-reading-questions
  weight: 120
- identifier: 579c055a-ccb4-eb7e-bb6b-f294146b45a5
  name: Readings
  url: /pages/readings/
  weight: 130
- identifier: 94de8151-483a-826f-90af-93d292b79cf2
  name: Class Slides
  url: /pages/class-slides
  weight: 140
- identifier: fed85a98-064c-2e2a-4378-f3f7549df9b8
  name: Assignments
  url: /pages/assignments/
  weight: 150
- identifier: ad95d694-8a5a-21e8-d68c-2ed80b877e38
  name: Exams
  url: /pages/exams
  weight: 160
- identifier: 795a5521-0a16-d54d-c4e8-910a0c21496f
  name: Studio Resources
  url: /pages/studio-resources
  weight: 170
- identifier: a4d4ed52-37df-946d-c2b1-9d114f44c277
  name: Related Resources
  url: /pages/related-resources
  weight: 180
